# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'payments with stripe' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for payments with stripe

  pod 'Stripe'

end
