//
//  PaymentIntentDataModel.swift
//  payments with stripe
//
//  Created by Shivam Maggu on 01/02/23.
//

import Foundation

// Handles the mapping of payment intent API's response

struct PaymentIntentDataModel: Decodable {
    
    // Customer ID for a new or existing user
    
    let customerId: String
    
    // Used for accessing customer's payment methods
    
    let ephemeralKey: String
    
    // A Secret key generated by the payment intent API
    // Used to process the payment
    
    let paymentIntent: String
    
    // Publishable key is used to initialize the SDK
    // This is necessary for opening AddressViewController or processing payments through PaymentSheet
    // Not required if key is already added to AppDelegate
    
    let publishableKey: String
}
